[package]
name = "cfir_calc"
version = "0.1.0"
authors = ["Cfir Tsabari <cfirt@sentinelone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
